AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Backend for site view counter
Globals:
  Function:
    Runtime: python3.8
    MemorySize: 128
Resources:
  ResumeFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ResumeFunction
      CodeUri: s3://onlineresumeprofile/e62b1822e7b339f0ac080ff4c51256ef
      Handler: src/handlers/lambda_function.lambda_handler
      Description: Backend for site view counter
      Timeout: 3
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: CounterTable
      Events:
        ResumeViews:
          Type: Api
          Properties:
            RestApiId:
              Ref: ResumeViewCountApi
            Path: /counter
            Method: get
  ResumeViewCountApi:
    Type: AWS::Serverless::Api
    Properties:
      Cors:
        AllowOrigin: '''http://d1hg85pd9j4a1a.cloudfront.net/index.html'''
      EndpointConfiguration: Regional
      OpenApiVersion: 3.0.1
      StageName: Prod
  CounterTable:
    Type: AWS::DynamoDB::Table
    Properties:
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      AttributeDefinitions:
      - AttributeName: siteviews
        AttributeType: S
      KeySchema:
      - AttributeName: siteviews
        KeyType: HASH
      TableName: countertable
